### ISSUE TITLE
URL specified in readme does not work

### ISSUE THREAD

**Issue by cds-amal** [illuzzig/besu-box#1]
Hi,

I was unable to get the box up. 

## versions
Truffle v5.1.29 (core: 5.1.29)
Solidity v0.5.16 (solc-js)
Node v10.20.1
Web3.js v1.2.1

# Notes

  - no need to run `npm install` because that command is already in `truffle-box.json`
  - should indicate commands need to be run in separate terminals
    - `npm run besu:docker`
    - `truffle migrate --network besu`
    - `npm run start:dev`
  - make url clickable in readme
      - [url doesn't work](http://localhost:3000/0xFE3B557E8Fb62b89F4916B721be55cEb828dBd73) 

![Screen Shot 2020-06-12 at 11 25 26 AM](https://user-images.githubusercontent.com/2529600/84518956-6efbe180-ac9f-11ea-9c2e-a4ff709b4918.png)

**Comment by illuzzig** [comment]
fixed: - clickable url

**Comment by illuzzig** [comment]
fixed: clickable url and broken link
